### ISSUE TITLE
Frontend exists?

### ISSUE THREAD

**Issue by LocalHeroPro** [mateusjunges/trackable-jobs-for-laravel#14]
Did you have prebuild frontend for that?

**Comment by mateusjunges** [comment]
Hi @LocalHeroPro, at this moment i don't have any frontend. I have plans to add it in the future, or you can submit a PR if you want to. Thanks!

**Comment by LocalHeroPro** [comment]
I'm familiar with Bootstrap 4, it's ok for that purpose?
Did you already have some mockup for that view?

**Comment by mateusjunges** [comment]
I don't have any mockup, but i think in something like the UI of the deployment pipeline on Laravel Vapor.

You  can check it in [this video](https://youtu.be/XsPeWjKAUt0?t=1231), or in the image below:

![image](https://user-images.githubusercontent.com/19756164/115450815-c4274e80-a1f2-11eb-9f5c-c2aae05ae18a.png)

**Comment by madalinignisca** [comment]
If you intend this, make it optional, requiring explicit install. Would not be nice to polute our admin panels with something that 99% will not fit our admin design.

Look at fortify as example, which is not forcing you to use the default blade/Vue components it has in. You must install them.

**Comment by mateusjunges** [comment]
@LocalHeroPro it still a work in progress, but you can install and test it if you want to:
https://github.com/mateusjunges/laravel-trackable-jobs-ui

```
composer require mateusjunges/laravel-trackable-jobs-ui
```

PRs are welcome!
