### ISSUE TITLE
exception on using the trait

### ISSUE THREAD

**Issue by AliBayat** [mateusjunges/trackable-jobs-for-laravel#15]
i try to use the trait on my job.

this is my job class:
```php
class LogJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels, Trackable;

	public string $info;

    public function __construct($info)
    {
         $this->info = $info;
    }

    public function handle()
    {
        \Log::info("Logged from job : ". $this->info);
		return "LogJob Complete Successfully";
    }


}
```

but when i dispatch the job, i get the following error:

Typed property App\Jobs\LogJob::$trackedJob must not be accessed before initialization {"exception":"[object] (Error(code: 0): Typed property App\\Jobs\\LogJob::$trackedJob must not be accessed before initialization at \\vendor\\mateusjunges\\laravel-trackable-jobs\\src\\Traits\\Trackable.php:36)

the job class works just fine without the trait included
and im using **database** for queue driver

**Comment by mateusjunges** [comment]
Hello @AliBayat, as explained in the readme, if you need to change your `__construct`, you need to use it as an alias from the trait, and call it from the constructor:
```php
class LogJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels, Trackable {
        __construct as __baseConstruct;
    }

    public string $info;

    public function __construct($info)
    {
         $this->info = $info;
         $this->__baseConstruct($info);
    }

    public function handle()
    {
        \Log::info("Logged from job : ". $this->info);
		return "LogJob Complete Successfully";
    }
}
```

It should solve your issue.

**Comment by mateusjunges** [comment]
Closing due to lack of updates. Feel free to reopen it if your problem persists.

**Comment by simonbuehler** [comment]
hi,

i am using the trait also when procesing batch  jobs dealing with some api, so e.g. i only pass in a `int` and a list array of Users.
so there is no `Model` involved, how could i handle this?
