### ISSUE TITLE
Output is 1 regardless of return value when queue connection is database

### ISSUE THREAD

**Issue by rxng** [mateusjunges/trackable-jobs-for-laravel#18]
I am using this on chained jobs and it works perfectly. However, there is an issue with return output value

When QUEUE_CONNECTION=sync and handle returns 'test'
Then output is correct in database as 'test'

When QUEUE_CONNECTION=database and handle returns 'test'
Then output is set to 1 in database (only the last chained job returns 'test')

**Comment by mateusjunges** [comment]
@rxng Thanks for reporting. I'll check it as soon as possible

**Comment by rxng** [comment]
@mateusjunges  thanks - what an odd issue!

**Comment by mateusjunges** [comment]
Hey @rxng, i've tested it here and it's working ok. Can you add your jobs to the issue? I have tested with this two:

First job:
```php
class TestJobChainOne implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
    use Trackable {
        __construct as baseConstruct;
    }


    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct(User $user)
    {
        $this->baseConstruct($user);
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        info('JOB 1');

        return $this->model->name;
    }
}
```

and this:

```php
class TestJobChainTwo implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
    use Trackable {
        __construct as baseConstruct;
    }


    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct(User $user)
    {
        $this->baseConstruct($user);
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        info('JOB 2');

        return $this->model->name;

    }
}
```

Then, i call these jobs with `Bus::chain`:
```php
$user = User::first();
$user1 = User::find(2);

Bus::chain([
    new TestJob($user),
    new TestJobChain($user1)
])->dispatch();
```

**Comment by mateusjunges** [comment]
@rxng any updates on this?

**Comment by tidcp** [comment]
@mateusjunges sorry for the delay, I had been away the past couple of days. I am not sure what changes I made but the issue has disappeared and I couldn't replicate it anymore. Really strange!

I will let you know if it turns up again specifically what is causing it. Do you know what might be the possible reasons it could have returned just the number 1 for all jobs except the last? Is there somewhere in the code that returns 1 by default? Just wondering for next time if it appears again.

**Comment by tidcp** [comment]
@mateusjunges also, is there a way to retry from a specific job in the chain? so that we can test more easily rather than trying to chain the whole list of jobs each time.

**Comment by rxng** [comment]
@mateusjunges sorry for the delay, I had been away the past couple of days. I am not sure what changes I made but the issue has disappeared and I couldn't replicate it anymore. Really strange!

I will let you know if it turns up again specifically what is causing it. Do you know what might be the possible reasons it could have returned just the number 1 for all jobs except the last? Is there somewhere in the code that returns 1 by default? Just wondering for next time if it appears again.

**Comment by rxng** [comment]
@mateusjunges also, is there a way to retry/resume from a specific job in the chain? It will help to test also, rather than trying to create new chain of the whole list of jobs each time.

**Comment by mateusjunges** [comment]
@rxng No, there is no `return 1` in this package. If your job doesn't return nothing, the output in the database will be null. 
About retry and resume jobs, since the aim of this package it to track jobs, it's currently not implemented here. 
I'll close this for now, but feel free to reopen it or create a new issue if the problem appears again. If so, add your jobs to the issue, hiding sensitive content if needed. Thanks!
