### ISSUE TITLE
ShouldBeUnique compatibility

### ISSUE THREAD

**Issue by faacsousa** [mateusjunges/trackable-jobs-for-laravel#20]
If a job implements ShouldBeUnique interface and the condition of the interface is met then the tracked job will remain with status queued.

Maybe the status 'failed' or a new status 'cancelled' would be more appropriate in this case.

**Comment by mateusjunges** [comment]
@faacsousa i think the better is to not track jobs that aren't dispatched. If a job implementst `ShouldBeUnique` and the condition matches, this job will not be dispatched by laravel. Do you have any fix for that in mind?
