### ISSUE TITLE
Potential to add prunable to base Model

### ISSUE THREAD

**Issue by bretto36** [mateusjunges/trackable-jobs-for-laravel#26]
https://laravel.com/docs/8.x/eloquent#pruning-models

Laravel supports auto pruning as of laravel 8, could this be added to the config? Otherwise the DB continues to grow

**Comment by mateusjunges** [comment]
Hello @bretto36. It's possible. I'll do it asap, but you can submit a PR if you want to.

**Comment by mateusjunges** [comment]
Closed with #27

**Comment by mateusjunges** [comment]
@bretto36 released in [v1.4.0](https://github.com/mateusjunges/trackable-jobs-for-laravel/tree/1.4.0)
