### ISSUE TITLE
Change the steps relationship name

### ISSUE THREAD

**Issue by nunomazer** [mateusjunges/trackable-jobs-for-laravel#43]
Hi my friend, greate package.

I would use it in one of my projetcs, but I'm using jog chaining and one of the models has a relatioship called `steps` alteady.  Could the steps relationship name be changed to `job_steps` ?

**Comment by mateusjunges** [comment]
Hey @nunomazer :wave:
Actually the `steps` relationship is not defined in this package (it's just an example in the readme), so you can rename it to whatever fits your use case :slightly_smiling_face:
