### ISSUE TITLE
Retry the failed job

### ISSUE THREAD

**Issue by giorgiopogliani** [mateusjunges/trackable-jobs-for-laravel#52]
Is there a way to manually retry the failed job? I have the tracked failed jobs in the tracked_jobs table but I don't have the actual job serialized

**Comment by DimaVIII** [comment]
@giorgiopogliani That's not the job of this package as it's only a tracking tool to display the jobs for some kind of frontend (possible for a end-user).
The current version release 1.7.0 does not support queue `job_id` which are needed to perform actions like `Retry the failed job` (you need to use the laravel api to perform actions).

The current master tree contains the new v2 version which supports queue `job_id` but it's a breaking change with no documentation yet.
https://github.com/mateusjunges/trackable-jobs-for-laravel/tree/master
