### ISSUE TITLE
$trackedJob must not be accessed before initialization

### ISSUE THREAD

**Issue by dipentatva** [mateusjunges/trackable-jobs-for-laravel#57]
I am getting below error for laravel 11

`[2024-09-08 06:39:49] local.ERROR: Typed property App\Jobs\ProcessClientInvoice::$trackedJob must not be accessed before initialization {"exception":"[object] (Error(code: 0): Typed property App\\Jobs\\ProcessClientInvoice::$trackedJob must not be accessed before initialization at C:\\wamp\\www\\web-app\\vendor\\mateusjunges\\laravel-trackable-jobs\\src\\Concerns\\Trackable.php:36)`

**Comment by dquirozswyft** [comment]
I have the same issue, can anybody give us a hand. thanks!

**Comment by mateusjunges** [comment]
This https://github.com/mateusjunges/trackable-jobs-for-laravel?tab=readme-ov-file#tracking-jobs should fix your issue.
