### ISSUE TITLE
Error in publish command

### ISSUE THREAD

**Issue by philippbuerger** [mateusjunges/trackable-jobs-for-laravel#58]
Hey, the publish command is trying to publish the migration `laravel_trackable_jobs_v2.php` but this file does not exists. 

When running the migration which was published I'm getting the following error:

![Bildschirmfoto 2024-11-25 um 14 42 25](https://github.com/user-attachments/assets/31e635fb-3e1e-4c3f-a39b-0dc05fca0793)

**Comment by mateusjunges** [comment]
thanks for reporting! I'll fix this one tomorrow

**Comment by mateusjunges** [comment]
should be fixed on v2.0.1

**Comment by philippbuerger** [comment]
Hi @mateusjunges the publish command now works thank you!

But not I'm getting the following issue when trying to run the migration:

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'after `name`, `attempts` int not null default '1' after `status`, `output` json ' at line 1 (Connection: mysql, SQL: create table `tracked_jobs` (`id` bigint unsigned not null auto_increment primary key, `trackable_id` varchar(255) null, `trackable_type` varchar(255) null, `name` varchar(255) not null, `status` varchar(255) null, `job_id` varchar(255) null after `name`, `attempts` int not null default '1' after `status`, `output` json null, `started_at` timestamp null, `finished_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')`

**Comment by mateusjunges** [comment]
@philippbuerger what mysql version are you using?
