### ISSUE TITLE
Can't publish config file

### ISSUE THREAD

**Issue by ckissi** [mateusjunges/trackable-jobs-for-laravel#6]
I've tried to publish config file after the install but got this:

![image](https://user-images.githubusercontent.com/5107590/115034318-a93f9c00-9ecb-11eb-9630-7ee893296538.png)

**Comment by mateusjunges** [comment]
Hello @ckissi!
Sorry about that, the path for the config file was wrong. Fixing it with #7.

**Comment by ckissi** [comment]
Thank you. it was super fast!
