### ISSUE TITLE
[FEATURE REQUEST] Allow to dispatch jobs without tracking

### ISSUE THREAD

**Issue by michabbb** [mateusjunges/trackable-jobs-for-laravel#8]
hi, i like the idea of this package. but when dealing with 100k of jobs, using it all the time is not that ideal. so i would like to ask if there is a way to tell the job by parameter if it´s trackable or not. in that case, i think, this package could be a great helper when it comes to debugging.

thanks.

**Comment by mateusjunges** [comment]
Hello @michabbb,

You mean add a new variable to the job and then check for this variable before tracking the job?

Something like this:
```php
namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Junges\TrackableJobs\Traits\Trackable;

class ProcessPodcastJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels, Trackable;
    
    private bool $trackable = false;

    public function handle()
    {
        //
    }
}
```

**Comment by michabbb** [comment]
yeah.... so let's say: default is "no tracking", but in case i need deep debugging so check my jobs, it would be nice if i could do 

`job::dispatch(.......,true)` <--- with tracking

instead of (default):

`job::dispatch(.....)` <--- without tracking

just an idea....

**Comment by johnnyfreeman** [comment]
What about something like this?

```php
// with tracking (default usage)
MyJob::dispatch(...);

// without tracking
MyJob::withoutTracking(function () {
    MyJob::dispatch(...);
});
```

This wouldn't introduce any breaking changes or require changes to the constructor. I can submit a PR if you'd like.

**Comment by michabbb** [comment]
hi @johnnyfreeman, thanks a lot for your offer. currently, I am not using this package, but if the development in one of my projects comes to a specific point, this package could be very useful. that´s the reason is asked about "optional tracking." so in other words, please don´t invest time only for me, only if you think, this might help other people as well 😏

**Comment by mateusjunges** [comment]
@johnnyfreeman you can sent a PR if you want to. Currently i'm developing the UI for this package, so i dont have time to work in this feature.

**Comment by mateusjunges** [comment]
Hey @michabbb and @johnnyfreeman can you guys please check PR #32? I'd appreciate your review.
